version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    build: ./MailSending-Backend
    container_name: MailSending-Backend
    ports:
      - "5020:5020"
    environment:
      - SMTP_HOST={SMTP_HOST}
      - SMTP_PORT={SMTP_PORT}
      - SMTP_USER={SMTP_USER}
      - SMTP_PASS={SMTP_PASS}
      - MONGODB_URI={MONGODB_URI}
      - JWT_SECRET={JWT_SECRET}
      - JWT_EXPIRES_IN={JWT_EXPIRES_IN}
      - NODE_ENV={NODE_ENV}  
      - BREVO_API_KEY={BREVO_API_KEY}
      - BREVO_SENDER_EMAIL={BREVO_SENDER_EMAIL}
      - MAILERSEND_API_KEY={MAILERSEND_API_KEY}
    depends_on:
      mongodb:
        condition: service_healthy

  frontend:
    build:
      context: ./MailSending-Frontend
      args:
        VITE_REACT_APP_BACKEND_BASEURL: https://mail-sending-backend.vercel.app
        # VITE_BASE_URL:  http://localhost:3020
    ports:
      - "3020:82"
    depends_on:
      - backend

volumes:
  mongodb_data: