version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    build: ./MailSending-Backend
    container_name: MailSending-Backend
    ports:
      - "5020:5020"
    environment:
      - MONGO_URI: mongodb://user:pass@mongodb:27017
      - PORT: 5020
      - NODE_ENV: production
    depends_on:
      mongodb:
        condition: service_healthy

  frontend:
    build:
      context: ./MailSending-Frontend
      args:
        VITE_REACT_APP_BACKEND_BASEURL: https://mail-sending-backend.vercel.app/
        # VITE_BASE_URL:  http://localhost:3020
    ports:
      - "3020:82"
    depends_on:
      - backend

volumes:
  mongodb_data: